# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19oQaV52z_ol-R5H-eZo0xt-I67qePAQ0

Write a python program to find the sum of tuple elements
Input : test_tup = (7, 8, 9, 1, 10, 7)

Output : 42
"""

test_tup = (7, 8, 9, 1, 10, 7)
sum = 0
for i in test_tup:
  sum += i

print(sum)