# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pffBIBoxoCrvKwHK7v06RXtoIAD7d6gt

**Reverse a list without using reverse() function**

Example:

INPUT: [1, 2, 3, 4, 5]

OUTPUT: [5, 4, 3, 2, 1]
"""

l1 = input("give the number list: ").split()
l2 = l1[::-1]
print(l2)